/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.lauttadev.diabetesassistant.gui;

import com.lauttadev.diabetesassistant.models.BloodSugar;
import com.lauttadev.diabetesassistant.models.Insulin;
import com.lauttadev.diabetesassistant.repositories.Database;
import java.awt.Component;
import java.util.ArrayList;
import javax.swing.SpringLayout;

/**
 *
 * @author Kristian
 */
public class AddBloodSugar extends javax.swing.JPanel {
    private final BloodSugar bloodsugar;
    private final Database<BloodSugar> database;
    private final ArrayList<Insulin> insulins;
    private final BloodSugarsTab panel;
    private final Component[] oldComponents;
    
    /**
     * Creates new form AddBloodSugar
     * @param bloodsugar
     * @param database
     * @param insulins
     * @param panel
     * @param oldComponents
     */
    public AddBloodSugar(BloodSugar bloodsugar, Database<BloodSugar> database, ArrayList<Insulin> insulins, BloodSugarsTab panel, Component[] oldComponents) {
        this.bloodsugar = bloodsugar;
        this.database = database;
        this.insulins = insulins;
        this.panel = panel;
        this.oldComponents = oldComponents;
        
        this.setLayout(new SpringLayout());
        initComponents();
        this.revalidate();
        this.repaint();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        insulin_label = new javax.swing.JLabel();
        insulins_box = new javax.swing.JComboBox();
        carbohydrate_label = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();

        insulin_label.setText("Valitse insuliini");
        insulin_label.setToolTipText("");

        insulins_box.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        carbohydrate_label.setText("Hiilihydraattien määrä");

        jButton1.setText("OK");

        jTextField1.setToolTipText("Kirjoita hiilihydraattien määrä muodossa: xx.xx");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1)
                    .addComponent(insulins_box, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(insulin_label)
                            .addComponent(carbohydrate_label))
                        .addGap(0, 201, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(insulin_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(insulins_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(carbohydrate_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel carbohydrate_label;
    private javax.swing.JLabel insulin_label;
    private javax.swing.JComboBox insulins_box;
    private javax.swing.JButton jButton1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

}
