/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.lauttadev.diabetesassistant.gui;

import com.lauttadev.diabetesassistant.models.Insulin;
import com.lauttadev.diabetesassistant.repositories.Database;
import java.awt.Color;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Locale;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.border.MatteBorder;

/**
 *
 * @author Kristian
 */
public class InsulinsTab extends javax.swing.JPanel {
    private Database<Insulin> insulinDatabase;
    
    /**
     * Creates new form InsulinsTab
     */
    public InsulinsTab(Database<Insulin> insulinDatabase) {
        this.insulinDatabase = insulinDatabase;
        
        initComponents();
        
        this.insulins_list.setLayout(new GridBagLayout());
        
        this.updateInsulinsList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        insulins_scroll_pane = new javax.swing.JScrollPane();
        insulins_list = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        add_insulin_text_field = new javax.swing.JTextField();
        add_insulin_button = new javax.swing.JButton();

        jSplitPane1.setDividerLocation(250);

        javax.swing.GroupLayout insulins_listLayout = new javax.swing.GroupLayout(insulins_list);
        insulins_list.setLayout(insulins_listLayout);
        insulins_listLayout.setHorizontalGroup(
            insulins_listLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 408, Short.MAX_VALUE)
        );
        insulins_listLayout.setVerticalGroup(
            insulins_listLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 283, Short.MAX_VALUE)
        );

        insulins_scroll_pane.setViewportView(insulins_list);

        jSplitPane1.setRightComponent(insulins_scroll_pane);

        jLabel1.setText("Ajastetut insuliinimuistutukset");

        jLabel2.setText("Muut insuliinit");

        add_insulin_button.setText("Lisää insuliini");
        add_insulin_button.setActionCommand("");
        add_insulin_button.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(0, 0, 0)));
        add_insulin_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                add_insulin_buttonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(add_insulin_text_field, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(add_insulin_button)))
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 355, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jSplitPane1)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(add_insulin_text_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(add_insulin_button))
                    .addContainerGap()))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void add_insulin_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add_insulin_buttonMouseClicked
        addInsulin();
    }//GEN-LAST:event_add_insulin_buttonMouseClicked

    /**
     * Add Insulin to database and list
     */
    private void addInsulin(){
        Insulin insulin = new Insulin(add_insulin_text_field.getText());
        insulinDatabase.add(insulin);
        
        addInsulinToList(insulin, true);
    }
    
    /**
     * Add Insulin to list
     * @param insulin
     * @param refresh 
     */
    private void addInsulinToList(final Insulin insulin, boolean refresh){
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.gridwidth = GridBagConstraints.REMAINDER;
        gbc.weightx = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        
        SimpleDateFormat formatter = new SimpleDateFormat("hh:mm", Locale.ENGLISH);
        JPanel paneeli = new JPanel();
        paneeli.add(new JLabel(insulin.getName() + " " + insulin.getPerCarbohydrate()));
        
        // Remove -Button
        final JButton btnRemove = new JButton("Poista");
        btnRemove.addActionListener(new ActionListener()
        {
            @Override
            public void actionPerformed(ActionEvent e)
            {
                insulinDatabase.delete(insulin);
                insulins_list.remove(btnRemove.getParent());
                insulins_list.revalidate();
                insulins_list.repaint();
            }
        });
        paneeli.add(btnRemove);
        
        paneeli.setBorder(new MatteBorder(0, 0, 1, 0, Color.GRAY));
        this.insulins_list.add(paneeli, gbc, 0);
        
        if(refresh){
            this.insulins_list.revalidate();
            this.insulins_list.repaint();
        }
    }
    
    /**
     * Update all Insulins to list
     */
    private void updateInsulinsList(){
        ArrayList<Insulin> il = this.insulinDatabase.all();
        
        this.insulins_list.removeAll();
        
        GridBagConstraints gbcTemp = new GridBagConstraints();
        gbcTemp.gridwidth = GridBagConstraints.REMAINDER;
        gbcTemp.weightx = 1;
        gbcTemp.weighty = 1;
        this.insulins_list.add(new JPanel(), gbcTemp);
        
        for (final Insulin i : il) {
            addInsulinToList(i, false);
        }
        
        this.insulins_list.revalidate();
        this.insulins_list.repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_insulin_button;
    private javax.swing.JTextField add_insulin_text_field;
    private javax.swing.JPanel insulins_list;
    private javax.swing.JScrollPane insulins_scroll_pane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
}
