/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.lauttadev.diabetesassistant.gui;

import com.lauttadev.diabetesassistant.Database;
import com.lauttadev.diabetesassistant.models.BloodSugar;
import java.awt.Font;
import java.awt.FontFormatException;
import java.awt.GraphicsEnvironment;
import java.awt.Label;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.Timer;

/**
 *
 * @author krislaut
 */
public class MainFrame extends javax.swing.JFrame {
    private Database db;
    
    /**
     * Creates new form MainFrame
     */
    public MainFrame(Database db) {
        this.db = db;
        
        initComponents();
        
        Timer t = new Timer(1000, new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e) {
                DateFormat df = new SimpleDateFormat("dd.MM.yyyy HH:mm");
                
                Date today = Calendar.getInstance().getTime();
                
                timestamp.setText(df.format(today));
            }
        });
        t.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainFrameTitle = new javax.swing.JLabel();
        add_bloodsugar = new javax.swing.JButton();
        bloodsugar = new javax.swing.JTextField();
        timestamp = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(500, 400));

        MainFrameTitle.setFont(new java.awt.Font("Ubuntu Light", 0, 15)); // NOI18N
        MainFrameTitle.setText("Diabetes Assistant");
        MainFrameTitle.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                MainFrameTitleComponentShown(evt);
            }
        });

        add_bloodsugar.setText("Lisää verensokeri");
        add_bloodsugar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                add_bloodsugarMouseClicked(evt);
            }
        });

        bloodsugar.setText("Verensokeri");

        timestamp.setText("Timestamp");
        timestamp.setName("timestamp"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(MainFrameTitle)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(timestamp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE)
                        .addComponent(bloodsugar, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(add_bloodsugar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MainFrameTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 321, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add_bloodsugar)
                    .addComponent(bloodsugar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(timestamp))
                .addContainerGap())
        );

        timestamp.getAccessibleContext().setAccessibleName("timeDisplay");
        timestamp.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MainFrameTitleComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_MainFrameTitleComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_MainFrameTitleComponentShown

    private void add_bloodsugarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add_bloodsugarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_add_bloodsugarMouseClicked
    
    private void addBloodSugar(){
        BloodSugar bloodSugar = new BloodSugar(this.bloodsugar.getText());
        db.addBloodSugar(bloodSugar);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel MainFrameTitle;
    private javax.swing.JButton add_bloodsugar;
    private javax.swing.JTextField bloodsugar;
    private javax.swing.JLabel timestamp;
    // End of variables declaration//GEN-END:variables
}
